---
driver:
  name: ec2
  require_chef_omnibus: 12.12.15

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-xxx
    transport:
      username: ubuntu
      ssh_key: ~/.ssh/xxx.pem

suites:
  - name: default
    run_list:
      - recipe[app-php-fpm::default]
    attributes:
